---
title: "Questools Documentation"
subtitle: "Questionnarie Tools."
author: "statCompTeam@bAIo-lab"
copyright: "statCompTeam@bAIo-lab"
output:
  packagedocs::package_docs:
    toc: true
    toc_collapse: false
redirect: http://bAIo-lab.github.io/Questools
vignette: |
  %\VignetteIndexEntry{Questools Documentation}
  %\VignetteEngine{packagedocs::redirect}
navpills: |
  <li class="active"><a href='index.html'>Docs</a></li>
  <li><a href='rd.html'>Package Ref</a></li>
  <li><a href='https://github.com/bAIo-lab/Questools'>Github <i class='fa fa-github'></i></a></li>
---

```{r global_options, include=FALSE}
# R output pre blocks are styled by default to indicate output
knitr::opts_chunk$set(comment = NA)

# shorthand for rd_link() - see ?packagedocs::rd_link for more information
rdl <- function(x) packagedocs::rd_link(deparse(substitute(x)))
```

# Questools

Questools is a visualization and analysis toolkit for Questionnaire datasets.  To use this package, you 
will need the R statistical computing environment (version 3.0 or later).
```{r echo=FALSE}
library("jpeg")
jj <- readJPEG("./figure/ques.jpeg",native=TRUE)
plot(0:1,0:1,type="n",ann=FALSE,axes=FALSE)
rasterImage(jj,0,0,1,1)
```

We highly recommend installation of **Questools** through our github.
For installation in R you can use devtools package:

```{r echo=TRUE, message=FALSE, warning=FALSE, eval=FALSE}
install.packages("devtools")
devtools::install_github("bAIo-lab/Questools")
library(Questools)
```

# Results
